name: deploy

on:
    push:
        branches:
            - main

jobs:
    deploy-laravel:
        runs-on: ubuntu-latest

        steps:
         - uses: actions/checkout@v2

         - name: Deploy to Lightsail
           uses: appleboy/ssh-action@mv1.0.3
           with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSHKEY }}
                script: "cd /home/ubuntu/deveops && ./laraveldeploy.sh"
